apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ordenes-compra
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-ordenes-compra
  template:
    metadata:
      labels:
        app: app-ordenes-compra
    spec:
      containers:
        - name: app-books
          image: nali1312/app-ordenes-compra
          env:
            - name: APP_CLIENTES_URL
              value: http://app-clientes-service:8080
            - name: APP_PRODUCTOS_URL
              value: http://app-producto-service:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-books-service
spec:
  type: ClusterIP
  selector:
    app: app-books
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080



